[project]
name = "hamrssv2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.54,<1.55",
    "pydantic>=2.11.9",
    "typer>=0.9.0",
    "requests>=2.32.0",
    "beautifulsoup4>=4.12.0",
]
