apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hamrss

labels:
  - includeSelectors: true
    pairs:
      app: hamrss

resources:
  - playwright.yaml
  - postgres.yaml
  - importer.yaml
  - publisher.yaml

configMapGenerator:
  - name: hamrss-config
    envs:
      - config/hamrss-config.env

images:
  - name: hamrss
    newName: ghcr.io/larsks/hamrss
    newTag: main
  - name: postgres
    newName: docker.io/postgres
    newTag: "18"
