apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamrss-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      component: hamrss-publisher
  template:
    metadata:
      labels:
        component: hamrss-publisher
    spec:
      enableServiceLinks: false
      containers:
        - name: hamrss-publisher
          image: hamrss:latest
          imagePullPolicy: Always
          command: ["uv", "run", "--no-sync", "--no-cache", "hamrss-publisher"]
          ports:
            - name: hamrss
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: hamrss-config
            - secretRef:
                name: hamrss-secrets
          env:
            - name: HAMRSS_PUBLISHER_HOST
              value: "0.0.0.0"
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "2"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: hamrss-publisher
spec:
  selector:
    component: hamrss-publisher
  ports:
    - port: 8080
      targetPort: hamrss
  type: ClusterIP
